workaround for the assembler error with gcc 4.9 Linaro toolchain
adding -Wa,-mimplicit-it=thumb option to AFLAGS fixes the following build
failure
Error: thumb conditional instruction should be in IT block

Conflicts:
	Makefile